;;; init --- Summary
;;; Commentary:
;;; Code:
(let ((file-name (expand-file-name "config.el" user-emacs-directory)))
  (if (file-exists-p file-name)
      (load-file file-name)))

(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

(require 'init-use-package)
(require 'init-emacs-tweaks)
(require 'init-dired)
(require 'init-calendar)
(require 'init-default-input-method)
(require 'init-helm)
(require 'init-git-integration)
(require 'init-completion)
(require 'init-org-mode)
(require 'init-org-capture)
(require 'init-org-agenda)
(require 'init-org-ref)
(require 'init-org-roam)
(require 'init-writeroom-mode)
(require 'init-tex-mode)
(require 'init-pdf-tools)
(require 'init-writegood-mode)
(require 'init-markdown-mode)
(require 'init-ibuffer)
(require 'init-gptel)
(require 'init-projectile)
(require 'init-expand-region)
(require 'init-ace-window)
(require 'init-undo-tree)
(require 'init-which-key)
(require 'init-beginend)
(require 'init-try)
(require 'init-csv-mode)
(require 'init-yasnippet)
(require 'init-eldoc)
(require 'init-prog-mode)
(require 'init-treesitter)
(require 'init-treemacs)
(require 'init-flycheck)
(require 'init-smartparens)
(require 'init-rainbow-delimiters)
(require 'init-lsp)
(require 'init-dap-mode)
(require 'init-graphviz-dot-mode)
(require 'init-docker)
(require 'init-python)
(require 'init-javascript)
(require 'init-xml)
(require 'init-sql)
(require 'init-yaml)
(require 'init-powershell)
(require 'init-po-mode)
(require 'init-elfeed)
(require 'init-org-re-reveal)
(require 'init-emacs-eye-candy)

(let ((file-name (expand-file-name "after-init.el" user-emacs-directory)))
  (when (file-exists-p file-name)
    (load-file file-name)))

;;; init.el ends here
